# Generated by Django 5.0.7 on 2024-08-13 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCalendar',
            fields=[
                ('share_cal_id', models.AutoField(primary_key=True, serialize=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to='calendars.calendar')),
                ('shared_users', models.ManyToManyField(related_name='shared_calendars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
