# Generated by Django 5.1 on 2024-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg_color',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
