# Generated by Django 5.1 on 2024-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeat_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_type',
            field=models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
