# Generated by Django 5.1 on 2024-08-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_end_time_event_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar',
            new_name='cal_id',
        ),
    ]
