# Generated by Django 5.1 on 2024-09-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_repeat_days_event_repeat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='repeated_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
