# Generated by Django 5.1 on 2024-09-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_repeated_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='repeat_days',
            new_name='repeat_details',
        ),
    ]
