# Generated by Django 5.1 on 2024-09-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_repeat_days_event_repeat_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='repeat_details',
            new_name='repeat_days',
        ),
    ]
