# Generated by Django 5.1 on 2024-09-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_repeat_details_event_repeat_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
