# Generated by Django 5.1 on 2024-08-23 00:07

import invitations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_calendarinvite_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarinvite',
            name='token',
            field=models.CharField(default=invitations.models.generate_token, max_length=50, unique=True),
        ),
    ]
