# Generated by Django 5.0.7 on 2024-08-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='/image/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
