# Generated by Django 5.1 on 2024-08-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="/Users/jasonhuang/My Coding Projects/headstarter/backend/media/image/default_profile.jpg",
                upload_to="profile_pics",
            ),
        ),
    ]
