# Generated by Django 5.0.7 on 2024-08-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='/app/media/image/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
