name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
      - '.VSCodeCounter'
      - 'Makefile'

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr
        run: |
          echo "${{ secrets.MY_PAT }}" | docker login ghcr.io --username jason-huang-dev --password-stdin

      - name: Create .env file
        run: |
          echo "VITE_GOOGLE_OAUTH_ID=${{ secrets.VITE_GOOGLE_OAUTH_ID }}" >> .env
          echo "VITE_GOOGLE_OAUTH_SECRET=${{ secrets.VITE_GOOGLE_OAUTH_SECRET }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env

      - name: Build Docker Backend Image
        run: |
          docker build -t ghcr.io/jason-huang-dev/backend-image:latest ./backend
          
      - name: Push Docker Backend Image
        run: |
          docker push ghcr.io/jason-huang-dev/backend-image:latest

      - name: Build Docker Frontend Image
        run: |
          docker build -t ghcr.io/jason-huang-dev/frontend-image:latest ./frontend
          
      - name: Push Docker Frontend Image
        run: |
          docker push ghcr.io/jason-huang-dev/frontend-image:latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Compose Images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker Compose Images
        run: |
          docker-compose -f docker-compose.yml push

      - name: Deploy Docker Images
        run: |
          echo "Deploying Docker images"
          # Add your deployment commands here
