name: Build TimeMesh

on:
  workflow_call:  # This allows the workflow to be called from other workflows
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
      - '.VSCodeCounter'
      - 'Makefile'

jobs:
  docker-build-timemesh:
    name: Docker Build TimeMesh
    uses: jason-huang-dev/headstarter/.github/workflows/docker-build-request.yaml@main
    permissions:
      contents: read
      packages: write  # Needed to push Docker image to GHCR
      pull-requests: write  # Needed to create and update comments in PRs
    with:
      # REQUIRED: Enable GHCR for pushing Docker images
      ghcr-enable: true

      # REQUIRED: List of Docker image names to build
      image-names: |
        ghcr.io/jason-huang-dev/headstarter

      # REQUIRED: Tag rules for the Docker images
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=raw,value=before,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=raw,value=after,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr

      # OPTIONAL: Path to the Docker context (default is root of repository)
      # context: .

      # OPTIONAL: Alternate Dockerfile name (default is Dockerfile)
      # file: Containerfile

      # OPTIONAL: Build stage to target (default is last stage in Dockerfile)
      # target:

      # OPTIONAL: Platforms to build for (default is linux/amd64)
      platforms: linux/amd64

      # OPTIONAL: Create a PR comment with image tags and labels (default is false)
      # comment-enable: false
