name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
      - '.VSCodeCounter'
      - 'Makefile'

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: |
          echo "VITE_GOOGLE_OAUTH_ID=${{ secrets.VITE_GOOGLE_OAUTH_ID }}" >> .env
          echo "VITE_GOOGLE_OAUTH_SECRET=${{ secrets.VITE_GOOGLE_OAUTH_SECRET }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env

      - name: Build Docker images with Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push

      - name: Deploy Docker images
        run: |
          echo "Deploying Docker images"
          # Add your deployment commands here
